/**
 * Recipe System Types
 *
 * Puck-compatible recipe format for page composition
 * Reference: https://puckeditor.com/docs/api-reference/data
 */

// ============================================================================
// SLOT CONTENT TYPES (for recipe data)
// ============================================================================

export type RecipeSlotType = 'text' | 'richtext' | 'image' | 'component' | 'list';

export interface RecipeSlotContent {
  type: RecipeSlotType;
  value: unknown;
  // For type='text': string
  // For type='richtext': PortableText[] or markdown string
  // For type='image': ImageValue
  // For type='component': BlockNode
  // For type='list': RecipeSlotContent[]
}

export interface ImageValue {
  src: string;
  alt: string;
  width?: number;
  height?: number;
}

// ============================================================================
// BLOCK NODE (Puck-compatible)
// ============================================================================

export interface BlockNode {
  // Puck-compatible identity
  type: string;                           // Component type (matches element registry ID)
  props: Record<string, unknown>;         // Component props

  // Puck readOnly zones for nested content
  readOnly?: Record<string, boolean>;

  // Our extensions (namespaced to avoid Puck conflicts)
  _uiMuseum?: {
    id: string;                           // Unique instance ID
    addedAt: string;                      // ISO timestamp
    addedBy: 'user' | 'ai';
    aiPrompt?: string;                    // If generated by AI
    slots?: Record<string, RecipeSlotContent>;  // Our slot system content
    hidden?: boolean;                     // Hide in preview
  };
}

// ============================================================================
// PAGE RECIPE (Puck-compatible)
// ============================================================================

export interface PageRecipe {
  // Identity
  id: string;                             // UUID
  version: string;                        // Schema version: "1.0.0"

  // Puck-compatible root configuration
  root: {
    props?: Record<string, unknown>;      // Root-level props
    theme?: string;                       // Theme override (our extension)
    className?: string;                   // Root container class
  };

  // Puck-compatible content array
  content: BlockNode[];                   // Main content blocks

  // Puck zones for drag-drop regions
  zones?: Record<string, BlockNode[]>;

  // Our extensions (namespaced)
  _uiMuseum: {
    name: string;                         // Recipe display name
    description?: string;                 // Recipe description
    category: RecipeCategory;             // Recipe category
    tags?: string[];                      // Searchable tags
    thumbnail?: string;                   // Preview image URL
    createdAt: string;                    // ISO timestamp
    updatedAt: string;                    // ISO timestamp
    createdBy: 'user' | 'ai';
    aiPrompt?: string;                    // If created by AI
  };
}

// ============================================================================
// RECIPE CATEGORIES
// ============================================================================

export type RecipeCategory =
  | 'landing'       // Landing pages (SaaS, product, marketing)
  | 'portfolio'     // Portfolio and showcase pages
  | 'pricing'       // Pricing and comparison pages
  | 'blog'          // Blog posts and articles
  | 'dashboard'     // Application dashboards
  | 'auth'          // Authentication pages
  | 'ecommerce'     // E-commerce pages
  | 'custom';       // User-created recipes

// ============================================================================
// RECIPE LAYOUTS
// ============================================================================

export type RecipeLayoutType = 'stack' | 'grid' | 'split' | 'sidebar';

export interface RecipeLayout {
  type: RecipeLayoutType;
  props?: {
    gap?: string;           // Tailwind spacing value
    columns?: number;       // For grid layout
    ratio?: string;         // For split layout (e.g., "1:2", "2:1")
    sidebarPosition?: 'left' | 'right';  // For sidebar layout
  };
}

// ============================================================================
// VALIDATION TYPES
// ============================================================================

export type ValidationErrorCode =
  | 'UNKNOWN_COMPONENT'
  | 'MISSING_REQUIRED_SLOT'
  | 'INVALID_PROP'
  | 'CIRCULAR_REFERENCE'
  | 'INVALID_SCHEMA'
  | 'MISSING_REQUIRED_FIELD';

export interface ValidationError {
  blockId?: string;
  field: string;
  message: string;
  code: ValidationErrorCode;
  path?: string;            // JSON path to the error
}

export interface ValidationWarning {
  blockId?: string;
  field: string;
  message: string;
  code: string;
}

export interface ValidationResult {
  valid: boolean;
  errors: ValidationError[];
  warnings: ValidationWarning[];
}

// ============================================================================
// RECIPE RENDERER PROPS
// ============================================================================

export interface RecipeRendererProps {
  recipe: PageRecipe;
  theme?: string;                         // Override recipe theme
  customTokens?: Record<string, string>;  // Custom CSS variable overrides
  onBlockClick?: (blockId: string) => void;  // For editor integration
  editMode?: boolean;                     // Enable edit mode styling
  className?: string;                     // Additional container class
}

export interface BlockRendererProps {
  block: BlockNode;
  onBlockClick?: (blockId: string) => void;
  editMode?: boolean;
}

// ============================================================================
// RECIPE METADATA (for listing/browsing)
// ============================================================================

export interface RecipeMetadata {
  id: string;
  name: string;
  description?: string;
  category: RecipeCategory;
  tags?: string[];
  thumbnail?: string;
  createdAt: string;
  updatedAt: string;
  createdBy: 'user' | 'ai';
  blockCount: number;
}

// ============================================================================
// HELPER TYPES
// ============================================================================

/**
 * Create a new block node with defaults
 */
export function createBlockNode(
  type: string,
  props: Record<string, unknown> = {},
  addedBy: 'user' | 'ai' = 'user'
): BlockNode {
  return {
    type,
    props,
    _uiMuseum: {
      id: `block-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      addedAt: new Date().toISOString(),
      addedBy,
    },
  };
}

/**
 * Create a new recipe with defaults
 */
export function createRecipe(
  name: string,
  category: RecipeCategory = 'custom',
  createdBy: 'user' | 'ai' = 'user'
): PageRecipe {
  const now = new Date().toISOString();
  return {
    id: `recipe-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    version: '1.0.0',
    root: {
      props: {},
    },
    content: [],
    _uiMuseum: {
      name,
      category,
      createdAt: now,
      updatedAt: now,
      createdBy,
    },
  };
}

/**
 * Extract metadata from a recipe
 */
export function getRecipeMetadata(recipe: PageRecipe): RecipeMetadata {
  return {
    id: recipe.id,
    name: recipe._uiMuseum.name,
    description: recipe._uiMuseum.description,
    category: recipe._uiMuseum.category,
    tags: recipe._uiMuseum.tags,
    thumbnail: recipe._uiMuseum.thumbnail,
    createdAt: recipe._uiMuseum.createdAt,
    updatedAt: recipe._uiMuseum.updatedAt,
    createdBy: recipe._uiMuseum.createdBy,
    blockCount: recipe.content.length,
  };
}
